5.0.1
HubSpot/hubspot-api-python pull request #103
Opened 2022-05-14 11:05 UTC by plaurynovich-hubspot

Issue https://github.com/HubSpot/hubspot-api-python/issues/101

2022-05-16 07:04 UTC, ksvirkou-hubspot requested changes
Could you update chengelog?

2022-05-17 08:40 UTC, atanasiuk-hubspot approved these changes

2022-05-17 10:45 UTC, ksvirkou-hubspot requested changes

2022-05-17 10:45 UTC, ksvirkou-hubspot commented on CHANGELOG.md
> +## [5.0.1](https://github.com/HubSpot/hubspot-api-python/compare/v5.0.0...v5.0.1) - 2022-05-14
Could you update the date ?

2022-05-17 11:04 UTC, merged